# Generated by Django 3.2.9 on 2021-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=0, upload_to='job/'),
            preserve_default=False,
        ),
    ]
