# Generated by Django 3.2.9 on 2021-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20211112_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(default=None),
        ),
    ]
