# Generated by Django 3.2.9 on 2021-11-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_application_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
    ]
